# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qRiversDialog
                                 A QGIS plugin
 Toolset to calculate river statistics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-06
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Evan Greenberg
        email                : egreenberg@ucsb.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
files = {
    'tree': 'tree_dialog_base.ui',
    'mask': 'mask_dialog_base.ui',
    'centerline': 'centerline_dialog_base.ui',
    'width': 'width_dialog_base.ui',
    'graph': 'graph_dialog_base.ui',
    'migration': 'migration_dialog_base.ui',
}
CLASSES = {}
for name, uifile in files.items():
    CLASSES[name], _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), uifile)
)


class treeDialog(QtWidgets.QDialog, CLASSES['tree']):
    def __init__(self, parent=None):
        """Constructor."""
        super(treeDialog, self).__init__(parent)
        self.setupUi(self)

class maskDialog(QtWidgets.QDialog, CLASSES['mask']):
    def __init__(self, parent=None):
        """Constructor."""
        super(maskDialog, self).__init__(parent)
        self.setupUi(self)

class centerlineDialog(QtWidgets.QDialog, CLASSES['centerline']):
    def __init__(self, parent=None):
        """Constructor."""
        super(centerlineDialog, self).__init__(parent)
        self.setupUi(self)

class widthDialog(QtWidgets.QDialog, CLASSES['width']):
    def __init__(self, parent=None):
        """Constructor."""
        super(widthDialog, self).__init__(parent)
        self.setupUi(self)

class graphDialog(QtWidgets.QDialog, CLASSES['graph']):
    def __init__(self, parent=None):
        """Constructor."""
        super(graphhDialog, self).__init__(parent)
        self.setupUi(self)

class migrationDialog(QtWidgets.QDialog, CLASSES['migration']):
    def __init__(self, parent=None):
        """Constructor."""
        super(migrationDialog, self).__init__(parent)
        self.setupUi(self)
